// Metadati paesi e mappatura codici ISO A3 — condivisi tra la mappa 2D
// (react-simple-maps) e il globo 3D (react-globe.gl). Copertura pressoché
// mondiale (stati sovrani ISO 3166-1, incluso Taiwan come destinazione
// tracciabile; escluse Antartide e i territori dipendenti disabitati/non
// autonomi, che non sono destinazioni di viaggio significative per questa
// app).

export const COUNTRY_META = {
  // --- Europa ---
  ITA: { name: "Italia", continent: "Europa" },
  FRA: { name: "Francia", continent: "Europa" },
  ESP: { name: "Spagna", continent: "Europa" },
  PRT: { name: "Portogallo", continent: "Europa" },
  DEU: { name: "Germania", continent: "Europa" },
  AUT: { name: "Austria", continent: "Europa" },
  CHE: { name: "Svizzera", continent: "Europa" },
  NLD: { name: "Paesi Bassi", continent: "Europa" },
  BEL: { name: "Belgio", continent: "Europa" },
  GBR: { name: "Regno Unito", continent: "Europa" },
  IRL: { name: "Irlanda", continent: "Europa" },
  GRC: { name: "Grecia", continent: "Europa" },
  HRV: { name: "Croazia", continent: "Europa" },
  CZE: { name: "Repubblica Ceca", continent: "Europa" },
  POL: { name: "Polonia", continent: "Europa" },
  HUN: { name: "Ungheria", continent: "Europa" },
  SVN: { name: "Slovenia", continent: "Europa" },
  NOR: { name: "Norvegia", continent: "Europa" },
  SWE: { name: "Svezia", continent: "Europa" },
  FIN: { name: "Finlandia", continent: "Europa" },
  DNK: { name: "Danimarca", continent: "Europa" },
  ISL: { name: "Islanda", continent: "Europa" },
  CYP: { name: "Cipro", continent: "Europa" },
  MLT: { name: "Malta", continent: "Europa" },
  ALB: { name: "Albania", continent: "Europa" },
  AND: { name: "Andorra", continent: "Europa" },
  BLR: { name: "Bielorussia", continent: "Europa" },
  BIH: { name: "Bosnia ed Erzegovina", continent: "Europa" },
  BGR: { name: "Bulgaria", continent: "Europa" },
  EST: { name: "Estonia", continent: "Europa" },
  LVA: { name: "Lettonia", continent: "Europa" },
  LIE: { name: "Liechtenstein", continent: "Europa" },
  LTU: { name: "Lituania", continent: "Europa" },
  LUX: { name: "Lussemburgo", continent: "Europa" },
  MDA: { name: "Moldavia", continent: "Europa" },
  MCO: { name: "Monaco", continent: "Europa" },
  MNE: { name: "Montenegro", continent: "Europa" },
  MKD: { name: "Macedonia del Nord", continent: "Europa" },
  ROU: { name: "Romania", continent: "Europa" },
  RUS: { name: "Russia", continent: "Europa" },
  SMR: { name: "San Marino", continent: "Europa" },
  SRB: { name: "Serbia", continent: "Europa" },
  SVK: { name: "Slovacchia", continent: "Europa" },
  UKR: { name: "Ucraina", continent: "Europa" },
  VAT: { name: "Città del Vaticano", continent: "Europa" },

  // --- Asia ---
  JPN: { name: "Giappone", continent: "Asia" },
  CHN: { name: "Cina", continent: "Asia" },
  THA: { name: "Thailandia", continent: "Asia" },
  VNM: { name: "Vietnam", continent: "Asia" },
  IDN: { name: "Indonesia", continent: "Asia" },
  IND: { name: "India", continent: "Asia" },
  TUR: { name: "Turchia", continent: "Asia" },
  ARE: { name: "Emirati Arabi Uniti", continent: "Asia" },
  ISR: { name: "Israele", continent: "Asia" },
  KOR: { name: "Corea del Sud", continent: "Asia" },
  AFG: { name: "Afghanistan", continent: "Asia" },
  ARM: { name: "Armenia", continent: "Asia" },
  AZE: { name: "Azerbaigian", continent: "Asia" },
  BHR: { name: "Bahrein", continent: "Asia" },
  BGD: { name: "Bangladesh", continent: "Asia" },
  BTN: { name: "Bhutan", continent: "Asia" },
  BRN: { name: "Brunei", continent: "Asia" },
  KHM: { name: "Cambogia", continent: "Asia" },
  GEO: { name: "Georgia", continent: "Asia" },
  IRN: { name: "Iran", continent: "Asia" },
  IRQ: { name: "Iraq", continent: "Asia" },
  JOR: { name: "Giordania", continent: "Asia" },
  KAZ: { name: "Kazakistan", continent: "Asia" },
  KWT: { name: "Kuwait", continent: "Asia" },
  KGZ: { name: "Kirghizistan", continent: "Asia" },
  LAO: { name: "Laos", continent: "Asia" },
  LBN: { name: "Libano", continent: "Asia" },
  MYS: { name: "Malaysia", continent: "Asia" },
  MDV: { name: "Maldive", continent: "Asia" },
  MNG: { name: "Mongolia", continent: "Asia" },
  MMR: { name: "Myanmar", continent: "Asia" },
  NPL: { name: "Nepal", continent: "Asia" },
  PRK: { name: "Corea del Nord", continent: "Asia" },
  OMN: { name: "Oman", continent: "Asia" },
  PAK: { name: "Pakistan", continent: "Asia" },
  PSE: { name: "Palestina", continent: "Asia" },
  PHL: { name: "Filippine", continent: "Asia" },
  QAT: { name: "Qatar", continent: "Asia" },
  SAU: { name: "Arabia Saudita", continent: "Asia" },
  SGP: { name: "Singapore", continent: "Asia" },
  LKA: { name: "Sri Lanka", continent: "Asia" },
  SYR: { name: "Siria", continent: "Asia" },
  TJK: { name: "Tagikistan", continent: "Asia" },
  TLS: { name: "Timor Est", continent: "Asia" },
  TKM: { name: "Turkmenistan", continent: "Asia" },
  UZB: { name: "Uzbekistan", continent: "Asia" },
  YEM: { name: "Yemen", continent: "Asia" },
  TWN: { name: "Taiwan", continent: "Asia" },

  // --- Nord America (incl. America Centrale e Caraibi) ---
  USA: { name: "Stati Uniti", continent: "Nord America" },
  CAN: { name: "Canada", continent: "Nord America" },
  MEX: { name: "Messico", continent: "Nord America" },
  CUB: { name: "Cuba", continent: "Nord America" },
  ATG: { name: "Antigua e Barbuda", continent: "Nord America" },
  BHS: { name: "Bahamas", continent: "Nord America" },
  BRB: { name: "Barbados", continent: "Nord America" },
  BLZ: { name: "Belize", continent: "Nord America" },
  CRI: { name: "Costa Rica", continent: "Nord America" },
  DMA: { name: "Dominica", continent: "Nord America" },
  DOM: { name: "Repubblica Dominicana", continent: "Nord America" },
  SLV: { name: "El Salvador", continent: "Nord America" },
  GRD: { name: "Grenada", continent: "Nord America" },
  GTM: { name: "Guatemala", continent: "Nord America" },
  HTI: { name: "Haiti", continent: "Nord America" },
  HND: { name: "Honduras", continent: "Nord America" },
  JAM: { name: "Giamaica", continent: "Nord America" },
  NIC: { name: "Nicaragua", continent: "Nord America" },
  PAN: { name: "Panama", continent: "Nord America" },
  KNA: { name: "Saint Kitts e Nevis", continent: "Nord America" },
  LCA: { name: "Saint Lucia", continent: "Nord America" },
  VCT: { name: "Saint Vincent e Grenadine", continent: "Nord America" },
  TTO: { name: "Trinidad e Tobago", continent: "Nord America" },

  // --- Sud America ---
  BRA: { name: "Brasile", continent: "Sud America" },
  ARG: { name: "Argentina", continent: "Sud America" },
  PER: { name: "Perù", continent: "Sud America" },
  CHL: { name: "Cile", continent: "Sud America" },
  COL: { name: "Colombia", continent: "Sud America" },
  BOL: { name: "Bolivia", continent: "Sud America" },
  ECU: { name: "Ecuador", continent: "Sud America" },
  GUY: { name: "Guyana", continent: "Sud America" },
  PRY: { name: "Paraguay", continent: "Sud America" },
  SUR: { name: "Suriname", continent: "Sud America" },
  URY: { name: "Uruguay", continent: "Sud America" },
  VEN: { name: "Venezuela", continent: "Sud America" },

  // --- Africa ---
  MAR: { name: "Marocco", continent: "Africa" },
  EGY: { name: "Egitto", continent: "Africa" },
  ZAF: { name: "Sudafrica", continent: "Africa" },
  TZA: { name: "Tanzania", continent: "Africa" },
  KEN: { name: "Kenya", continent: "Africa" },
  DZA: { name: "Algeria", continent: "Africa" },
  AGO: { name: "Angola", continent: "Africa" },
  BEN: { name: "Benin", continent: "Africa" },
  BWA: { name: "Botswana", continent: "Africa" },
  BFA: { name: "Burkina Faso", continent: "Africa" },
  BDI: { name: "Burundi", continent: "Africa" },
  CPV: { name: "Capo Verde", continent: "Africa" },
  CMR: { name: "Camerun", continent: "Africa" },
  CAF: { name: "Repubblica Centrafricana", continent: "Africa" },
  TCD: { name: "Ciad", continent: "Africa" },
  COM: { name: "Comore", continent: "Africa" },
  COG: { name: "Congo", continent: "Africa" },
  COD: { name: "Congo (RDC)", continent: "Africa" },
  CIV: { name: "Costa d'Avorio", continent: "Africa" },
  DJI: { name: "Gibuti", continent: "Africa" },
  GNQ: { name: "Guinea Equatoriale", continent: "Africa" },
  ERI: { name: "Eritrea", continent: "Africa" },
  SWZ: { name: "Eswatini", continent: "Africa" },
  ETH: { name: "Etiopia", continent: "Africa" },
  GAB: { name: "Gabon", continent: "Africa" },
  GMB: { name: "Gambia", continent: "Africa" },
  GHA: { name: "Ghana", continent: "Africa" },
  GIN: { name: "Guinea", continent: "Africa" },
  GNB: { name: "Guinea-Bissau", continent: "Africa" },
  LSO: { name: "Lesotho", continent: "Africa" },
  LBR: { name: "Liberia", continent: "Africa" },
  LBY: { name: "Libia", continent: "Africa" },
  MDG: { name: "Madagascar", continent: "Africa" },
  MWI: { name: "Malawi", continent: "Africa" },
  MLI: { name: "Mali", continent: "Africa" },
  MRT: { name: "Mauritania", continent: "Africa" },
  MUS: { name: "Mauritius", continent: "Africa" },
  MOZ: { name: "Mozambico", continent: "Africa" },
  NAM: { name: "Namibia", continent: "Africa" },
  NER: { name: "Niger", continent: "Africa" },
  NGA: { name: "Nigeria", continent: "Africa" },
  RWA: { name: "Ruanda", continent: "Africa" },
  STP: { name: "São Tomé e Príncipe", continent: "Africa" },
  SEN: { name: "Senegal", continent: "Africa" },
  SYC: { name: "Seychelles", continent: "Africa" },
  SLE: { name: "Sierra Leone", continent: "Africa" },
  SOM: { name: "Somalia", continent: "Africa" },
  SSD: { name: "Sudan del Sud", continent: "Africa" },
  SDN: { name: "Sudan", continent: "Africa" },
  TGO: { name: "Togo", continent: "Africa" },
  TUN: { name: "Tunisia", continent: "Africa" },
  UGA: { name: "Uganda", continent: "Africa" },
  ZMB: { name: "Zambia", continent: "Africa" },
  ZWE: { name: "Zimbabwe", continent: "Africa" },

  // --- Oceania ---
  AUS: { name: "Australia", continent: "Oceania" },
  NZL: { name: "Nuova Zelanda", continent: "Oceania" },
  FJI: { name: "Figi", continent: "Oceania" },
  KIR: { name: "Kiribati", continent: "Oceania" },
  MHL: { name: "Isole Marshall", continent: "Oceania" },
  FSM: { name: "Micronesia", continent: "Oceania" },
  NRU: { name: "Nauru", continent: "Oceania" },
  PLW: { name: "Palau", continent: "Oceania" },
  PNG: { name: "Papua Nuova Guinea", continent: "Oceania" },
  WSM: { name: "Samoa", continent: "Oceania" },
  SLB: { name: "Isole Salomone", continent: "Oceania" },
  TON: { name: "Tonga", continent: "Oceania" },
  TUV: { name: "Tuvalu", continent: "Oceania" },
  VUT: { name: "Vanuatu", continent: "Oceania" },
};

export const NAME_TO_A3 = {};
for (const [a3, m] of Object.entries(COUNTRY_META)) NAME_TO_A3[m.name.toLowerCase()] = a3;
Object.assign(NAME_TO_A3, {
  "regno unito": "GBR", "inghilterra": "GBR", "uk": "GBR",
  "stati uniti d'america": "USA", "usa": "USA", "america": "USA",
  "paesi bassi": "NLD", "olanda": "NLD",
  "repubblica ceca": "CZE", "cechia": "CZE",
  "birmania": "MMR",
  "città del vaticano": "VAT", "vaticano": "VAT",
  "corea": "KOR",
  "repubblica democratica del congo": "COD", "rd congo": "COD",
});

export const NUM_TO_A3 = {
  // --- Europa ---
  "380": "ITA", "250": "FRA", "724": "ESP", "620": "PRT", "276": "DEU",
  "040": "AUT", "756": "CHE", "528": "NLD", "056": "BEL", "826": "GBR",
  "372": "IRL", "300": "GRC", "191": "HRV", "203": "CZE", "616": "POL",
  "348": "HUN", "705": "SVN", "578": "NOR", "752": "SWE", "246": "FIN",
  "208": "DNK", "352": "ISL", "196": "CYP", "470": "MLT",
  "008": "ALB", "020": "AND", "112": "BLR", "070": "BIH", "100": "BGR",
  "233": "EST", "428": "LVA", "438": "LIE", "440": "LTU", "442": "LUX",
  "498": "MDA", "492": "MCO", "499": "MNE", "807": "MKD", "642": "ROU",
  "643": "RUS", "674": "SMR", "688": "SRB", "703": "SVK", "804": "UKR",
  "336": "VAT",

  // --- Asia ---
  "392": "JPN", "156": "CHN", "764": "THA", "704": "VNM", "360": "IDN",
  "356": "IND", "792": "TUR", "784": "ARE", "376": "ISR", "410": "KOR",
  "004": "AFG", "051": "ARM", "031": "AZE", "048": "BHR", "050": "BGD",
  "064": "BTN", "096": "BRN", "116": "KHM", "268": "GEO", "364": "IRN",
  "368": "IRQ", "400": "JOR", "398": "KAZ", "414": "KWT", "417": "KGZ",
  "418": "LAO", "422": "LBN", "458": "MYS", "462": "MDV", "496": "MNG",
  "104": "MMR", "524": "NPL", "408": "PRK", "512": "OMN", "586": "PAK",
  "275": "PSE", "608": "PHL", "634": "QAT", "682": "SAU", "702": "SGP",
  "144": "LKA", "760": "SYR", "762": "TJK", "626": "TLS", "795": "TKM",
  "860": "UZB", "887": "YEM", "158": "TWN",

  // --- Nord America ---
  "840": "USA", "124": "CAN", "484": "MEX", "192": "CUB",
  "028": "ATG", "044": "BHS", "052": "BRB", "084": "BLZ", "188": "CRI",
  "212": "DMA", "214": "DOM", "222": "SLV", "308": "GRD", "320": "GTM",
  "332": "HTI", "340": "HND", "388": "JAM", "558": "NIC", "591": "PAN",
  "659": "KNA", "662": "LCA", "670": "VCT", "780": "TTO",

  // --- Sud America ---
  "076": "BRA", "032": "ARG", "604": "PER", "152": "CHL", "170": "COL",
  "068": "BOL", "218": "ECU", "328": "GUY", "600": "PRY", "740": "SUR",
  "858": "URY", "862": "VEN",

  // --- Africa ---
  "504": "MAR", "818": "EGY", "710": "ZAF", "834": "TZA", "404": "KEN",
  "012": "DZA", "024": "AGO", "204": "BEN", "072": "BWA", "854": "BFA",
  "108": "BDI", "132": "CPV", "120": "CMR", "140": "CAF", "148": "TCD",
  "174": "COM", "178": "COG", "180": "COD", "384": "CIV", "262": "DJI",
  "226": "GNQ", "232": "ERI", "748": "SWZ", "231": "ETH", "266": "GAB",
  "270": "GMB", "288": "GHA", "324": "GIN", "624": "GNB", "426": "LSO",
  "430": "LBR", "434": "LBY", "450": "MDG", "454": "MWI", "466": "MLI",
  "478": "MRT", "480": "MUS", "508": "MOZ", "516": "NAM", "562": "NER",
  "566": "NGA", "646": "RWA", "678": "STP", "686": "SEN", "690": "SYC",
  "694": "SLE", "706": "SOM", "728": "SSD", "729": "SDN", "768": "TGO",
  "788": "TUN", "800": "UGA", "894": "ZMB", "716": "ZWE",

  // --- Oceania ---
  "036": "AUS", "554": "NZL",
  "242": "FJI", "296": "KIR", "584": "MHL", "583": "FSM", "520": "NRU",
  "585": "PLW", "598": "PNG", "882": "WSM", "090": "SLB", "776": "TON",
  "798": "TUV", "548": "VUT",
};

export function a3FromGeo(geo) {
  const raw = String(geo.id);
  return NUM_TO_A3[raw.padStart(3, "0")] || NUM_TO_A3[raw] || null;
}
