// Emoji rappresentativa per ciascuna Milestone, usata solo dalla Mappa 3D
// (Globe3D.jsx) quando lo zoom è abbastanza ravvicinato. Puramente
// presentazionale: non fa parte dei dati "canonici" della milestone
// (src/milestones.js), che restano usati anche da altre parti dell'app
// (pagina Milestone, sincronizzazione Turso).
//
// Le milestone non presenti qui sotto usano DEFAULT_MILESTONE_EMOJI.

export const MILESTONE_EMOJIS = {
  "torre-eiffel": "🗼",
  "colosseo": "🏛️",
  "pantheon-roma": "🏛️",
  "torre-di-pisa": "🗼",
  "sagrada-familia": "⛪",
  "alhambra": "🏰",
  "stonehenge": "🪨",
  "big-ben": "🕰️",
  "acropoli-atene": "🏛️",
  "san-basilio": "⛪",
  "neuschwanstein": "🏰",
  "porta-brandeburgo": "🏛️",
  "piazza-san-marco": "🏛️",
  "versailles": "🏰",
  "duomo-milano": "⛪",
  "louvre": "🖼️",
  "notre-dame": "⛪",
  "cremlino": "🏰",
  "buckingham-palace": "🏰",
  "fontana-di-trevi": "⛲",
  "castel-sant-angelo": "🏰",
  "duomo-firenze": "⛪",
  "ponte-di-rialto": "🌉",
  "torre-di-londra": "🏰",
  "london-eye": "🎡",
  "duomo-colonia": "⛪",
  "castello-di-praga": "🏰",
  "ponte-carlo-praga": "🌉",
  "mont-saint-michel": "⛪",
  "scogliere-di-moher": "🏞️",
  "palazzo-reale-madrid": "🏰",
  "torre-de-belem": "🏰",
  "grande-muraglia": "🧱",
  "citta-proibita": "🏯",
  "esercito-terracotta": "🗿",
  "taj-mahal": "🕌",
  "angkor-wat": "🛕",
  "petra": "🏛️",
  "hagia-sophia": "🕌",
  "moschea-blu": "🕌",
  "burj-khalifa": "🏙️",
  "palazzo-del-potala": "🏯",
  "monte-fuji": "🗻",
  "tempio-oro-amritsar": "🛕",
  "fushimi-inari": "⛩️",
  "tempio-senso-ji": "⛩️",
  "torre-di-tokyo": "🗼",
  "marina-bay-sands": "🏙️",
  "petronas-towers": "🏙️",
  "borobudur": "🛕",
  "wat-arun": "🛕",
  "grand-palace-bangkok": "🏯",
  "muro-del-pianto": "🕍",
  "cupola-della-roccia": "🕌",
  "palazzo-topkapi": "🏯",
  "baia-di-halong": "🏞️",
  "statua-liberta": "🗽",
  "monte-rushmore": "🏔️",
  "golden-gate": "🌉",
  "cascate-niagara": "🌊",
  "chichen-itza": "🛕",
  "empire-state": "🏙️",
  "cn-tower": "🗼",
  "times-square": "🌆",
  "ponte-di-brooklyn": "🌉",
  "casa-bianca": "🏛️",
  "campidoglio-usa": "🏛️",
  "hollywood-sign": "🎬",
  "space-needle": "🗼",
  "grand-canyon": "🏞️",
  "alcatraz": "🔒",
  "cristo-redentore": "✝️",
  "machu-picchu": "⛰️",
  "moai-isola-pasqua": "🗿",
  "cascate-iguazu": "🌊",
  "salar-de-uyuni": "🧂",
  "isole-galapagos": "🐢",
  "perito-moreno": "🧊",
  "torres-del-paine": "⛰️",
  "copacabana": "🏖️",
  "pan-di-zucchero": "⛰️",
  "cartagena-centro-storico": "🏘️",
  "obelisco-buenos-aires": "🏛️",
  "piramidi-giza": "🔺",
  "sfinge-giza": "🗿",
  "table-mountain": "⛰️",
  "cascate-vittoria": "🌊",
  "jemaa-el-fna": "🎪",
  "serengeti": "🦁",
  "kilimangiaro": "🏔️",
  "dune-di-merzouga": "🏜️",
  "chefchaouen": "🔵",
  "saqqara": "🔺",
  "abu-simbel": "🗿",
  "valle-dei-re": "⚱️",
  "robben-island": "🏝️",
  "stone-town-zanzibar": "🏘️",
  "sydney-opera-house": "🎭",
  "uluru": "🪨",
  "sydney-harbour-bridge": "🌉",
  "grande-barriera-corallina": "🐠",
  "milford-sound": "🏞️",
  "hobbiton": "🎬",
  "bora-bora": "🏝️",
  "twelve-apostles": "🪨",
  "whitsunday-islands": "🏝️",
  "waitomo-caves": "🕳️",
};

export const DEFAULT_MILESTONE_EMOJI = "📍";
